from .fake import FakeAudioInput, FakeAudioOutput
from .interfaces import AudioInput, AudioOutput
from .playback_queue import (
    ABQueuedPlaybackOutput,
    DEFAULT_MAX_CHUNKS,
    PlaybackTimingStats,
    QueuedPlaybackOutput,
)
from .capture_ux import (
    COUNTDOWN_SECONDS,
    PROGRESS_BAR_WIDTH,
    emit_analysis_complete,
    emit_analysis_start,
    emit_capture_complete,
    emit_capture_failed,
    finish_progress_line,
    format_clock_duration,
    render_progress_bar,
    run_countdown,
    update_recording_progress,
)
from .independent_mic import (
    CAPTURE_CONDITIONS as INDEPENDENT_CAPTURE_CONDITIONS,
    DeviceStreamCapture,
    IndependentCaptureResult,
    IndependentMicConfig,
    IndependentPairAnalysis,
    analyze_independent_pair,
    record_independent_microphones,
    validate_input_device,
)
from .multimic import (
    ChannelPairAnalysis,
    ChannelRouter,
    DualMicResidualFrame,
    MultiChannelAudioInput,
    MultiMicConfig,
    RoutedPrimaryAudioInput,
    analyze_channel_pair,
    compute_correlation,
    compute_peak,
    compute_rms,
    estimate_relative_delay_samples,
)
from .pipeline import StreamingPipeline
from .recorder import (
    LiveInstrumentation,
    LiveRecordingPaths,
    LiveStreamRecorder,
    create_live_recorder,
    create_live_session_dir,
)
from .replay import (
    DEFAULT_REPLAY_CHUNK_SIZE,
    ReplayResult,
    load_session_chunk_size,
    replay_wav_file,
    replay_wav_through_enhancer,
)
from .sounddevice_multimic import (
    DualMicCaptureResult,
    FakeMultiChannelAudioInput,
    SoundDeviceMultiChannelInput,
    record_dual_microphone,
)
from .sounddevice_backend import (
    SoundDeviceAudioInput,
    SoundDeviceAudioOutput,
    SoundDeviceDuplexSession,
    SoundDeviceStreamStats,
    close_sounddevice_io,
    close_sounddevice_output,
    downmix_to_mono,
    format_device_listing,
    list_audio_devices,
    open_sounddevice_io,
    open_sounddevice_output,
    upmix_mono_to_channels,
)

__all__ = [
    "AudioInput",
    "AudioOutput",
    "ChannelPairAnalysis",
    "ChannelRouter",
    "COUNTDOWN_SECONDS",
    "DeviceStreamCapture",
    "DualMicCaptureResult",
    "DualMicResidualFrame",
    "FakeAudioInput",
    "FakeAudioOutput",
    "FakeMultiChannelAudioInput",
    "INDEPENDENT_CAPTURE_CONDITIONS",
    "IndependentCaptureResult",
    "IndependentMicConfig",
    "IndependentPairAnalysis",
    "LiveInstrumentation",
    "LiveRecordingPaths",
    "LiveStreamRecorder",
    "ABQueuedPlaybackOutput",
    "QueuedPlaybackOutput",
    "MultiMicConfig",
    "ReplayResult",
    "RoutedPrimaryAudioInput",
    "SoundDeviceAudioInput",
    "SoundDeviceAudioOutput",
    "SoundDeviceDuplexSession",
    "SoundDeviceMultiChannelInput",
    "SoundDeviceStreamStats",
    "StreamingPipeline",
    "analyze_channel_pair",
    "analyze_independent_pair",
    "close_sounddevice_io",
    "close_sounddevice_output",
    "compute_correlation",
    "compute_peak",
    "compute_rms",
    "create_live_recorder",
    "create_live_session_dir",
    "DEFAULT_MAX_CHUNKS",
    "estimate_relative_delay_samples",
    "load_session_chunk_size",
    "record_dual_microphone",
    "record_independent_microphones",
    "replay_wav_file",
    "replay_wav_through_enhancer",
    "validate_input_device",
    "downmix_to_mono",
    "format_device_listing",
    "list_audio_devices",
    "open_sounddevice_io",
    "open_sounddevice_output",
    "upmix_mono_to_channels",
]
